[package]
name = "warlock"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.8.3",features = ["multipart", "ws"]}
bcrypt = "0.17.0"
clap = {version="4.5.35",features = ["derive"]}
config = "0.15.11"
lazy_static = "1.5.0"
redis = { version = "0.29.2", features = ["tokio-comp"] }
sea-orm = "1.1.8"
serde = {version = "1.0.219", features = ["derive"]}
thiserror = {version = "2.0.12"}
time ={version =  "0.3.41",features = ["formatting", "parsing", "macros", "std", "local-offset","serde"]}
tokio = {version = "1.44.1", features = ["full"]}
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "local-time"] }

