//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::book::Entity as Book;
pub use super::tag::Entity as Tag;
pub use super::uploads::Entity as Uploads;
pub use super::users::Entity as Users;
