[app]
app_name="warlock"
host="127.0.0.1"
port=8080

[log]
level="debug"
dir="logs"
log_file="warlock.log"

[db]
type="mysql"
host="127.0.0.1"
port=3306
user="root"
password="123456"
database="warlock"


[redis]
host="127.0.0.1"
port=6379

