name: Build for x86_64-unknown-linux-musl

on:
  push:
    branches: [ "master" ]  # 触发分支
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Linux 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl  # 指定目标平台
          override: true

      - name: Build (Release)
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-binary
          path: target/x86_64-unknown-linux-musl/release/warlock
